### ISSUE TITLE
project5-zfr-submission

### ISSUE THREAD

**Issue by amirl1086** [oronsa/shoulder2shoulder#14]
- Project: Accounting Shoulder
- Team:
  - Oron Sason
  - Amir Lavi 
  - Shimri Peretz
  - Maein Abu Gosh
- [Link to the ZFR](https://github.com/oronsa/shoulder2shoulder/wiki/ZFR)
- [Link to User manual](https://github.com/oronsa/shoulder2shoulder/wiki/user-manual)
- [Link to Developers manual](https://github.com/oronsa/shoulder2shoulder/wiki/developers-manual)

@ItamarShDev

**Comment by robi-y** [comment]
- add MSs
- attach issues to MSs
