### ISSUE TITLE
Iteration 1 - MVP

### ISSUE THREAD

**Issue by amirl1086** [oronsa/shoulder2shoulder#16]
#### Iteration page: [here](https://github.com/oronsa/shoulder2shoulder/wiki/MVP)
- Iteration page updated, including:
  - [x] Present the Iteration goals
  - [x] Present the team members roles
  - [x] Present the main stories For The Current Iteration
  - [x] Creating specific diagrams, zoom-in point of view
  - [ ] Client review - pending
- Next Iteration:
  - [x] Open page 
  - [x] Present the Iteration goals<br><br>
- [x] Git tag<br><br>
- Submitted
  - [x] Announcement in chat room
  - [x] Assign this issue to checker
  - [x] Register for a review meeting

Submitted by: Amir Lavi, Oron Sason, Shimri Peretz and Maein Abu Gosh

@ItamarShDev

**Comment by ItamarShDev** [comment]
:+1: 
Tag me when the client review is done

**Comment by ItamarShDev** [comment]
any news?

**Comment by oronsa** [comment]
We did some things  soon I  will update the issues board @ItamarShDev
