### ISSUE TITLE
Iteration 2: MVP-Take 2

### ISSUE THREAD

**Issue by oronsa** [oronsa/shoulder2shoulder#18]
#### Iteration page: [here](https://github.com/oronsa/shoulder2shoulder/wiki/MVP_take2)
- Iteration page updated, including:
  - [x] Present the Iteration goals
  - [x] Present the team members roles
  - [ ] Client review - pending
- Next Iteration:
  - [ ] Open page 
  - [ ] Present the Iteration goals<br><br>
  - [x] Git tag<br><br>
- Submitted
  - [x] Assign this issue to checker
  - [x] Register for a review meeting

Submitted by: Amir Lavi, Oron Sason, Shimri Peretz and Maein Abu Gosh

@ItamarShDev

**Comment by ItamarShDev** [comment]
iteration conclusion is not updated yet, when will it be?

also why have you called it mvp take 2?

**Comment by oronsa** [comment]
After discussing this issue with Reuven, he told us to continue the current one but on a different iteration, the tasks remains the same so we gave it a similar name with an addition.
We wrote the final conclusions on the previous iteration. The conclusions are not suppose to come at the end? @ItamarShDev
