### ISSUE TITLE
Inception Review

### ISSUE THREAD

**Issue by robi-y** [oronsa/shoulder2shoulder#2]
Hi
Nice work, some comments
- Readme
  - update repo summary (in settings)
  - No deployment site (also need to link from projects list
  - broken link to idea report
- Team Page: how will you communicate inside the group?
- Excellent inception page
  Good luck (adding @ItamarShDev )

**Comment by oronsa** [comment]
ראובן  שלום,
1.בלינק של רעיון הפרויקט הקישור עובד הוא פשוט נפתח כאשר לוחצים על
 presentation
- Project Idea https://github.com/oronsa/shoulder2shoulder/wiki/ (
  Presentation
  https://github.com/oronsa/shoulder2shoulder/blob/master/Doc/The%20general%20idea.pptx
  )
1. לא הבנתי מה לעשות בהגדרות לגבי repo  אשמח להסבר
   3.אשמח לקבל ציון משום מה אין לנו ציון בדף הציונים של משימה מס' 2 מאמין שזה
   קשור לאיחור בהגשה (שהיה באישור ותיאום איתך , המשך יום מוצלח ושבת שלום

2016-03-17 8:13 GMT+02:00 robi-y notifications@github.com:
