### ISSUE TITLE
Iteration 2: Test Driven Development

### ISSUE THREAD

**Issue by amirl1086** [oronsa/shoulder2shoulder#26]
#### Iteration page: [here](https://github.com/oronsa/shoulder2shoulder/wiki/TDD)
- Iteration page updated, including:
  - [x] Present the Iteration goals
  - [x] Present the team members roles
  - [x] Main Stories For The Current Iteration
- [ ] Client review - scrum over the phone, raw product will be shown on next week meeting
- Next Iteration:
  - [x] Open page 
  - [x] Present the Iteration goals
  - [x] Git tag
- Submitted
  - [x] Assign this issue to checker
  - [x] Register for a review meeting

Submitted by: Amir Lavi, Oron Sason, Shimri Peretz and Maein Abu Gosh

@ItamarShDev

**Comment by ItamarShDev** [comment]
what about testing?
