### ISSUE TITLE
project3-srs-submission and angular team mission

### ISSUE THREAD

**Issue by oronsa** [oronsa/shoulder2shoulder#3]
- Team:
  - Oron Sason
  - Amir Lavi 
  - Shimri Peretz
  - Maein Abu Gosh
- [Link to the SRS](https://github.com/oronsa/shoulder2shoulder/wiki/SRS/)
- [distribution Link](http://accountingshoulder.azurewebsites.net/)
  
  @robi-y @ItamarShDev

**Comment by ItamarShDev** [comment]
:+1:
